

[server]
enableCORS=true
enableXsrfProtection=true
maxUploadSize = 5000
maxMessageSize = 5000

# [server.sharing]
# enable=true





[theme]
base="light"
backgroundColor="#F0F0F0"
#primaryColor="#027ed1"     # Example accent color
#secondaryBackgroundColor="#FFFFFF"
# textColor="#222222"
# font="Tahoma"





